DROP TABLE IF EXISTS poet CASCADE;
DROP TABLE IF EXISTS poems;

CREATE TABLE poet (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
    poet TEXT NOT NULL UNIQUE,
    date_of_birth INTEGER NOT NULL,
    date_of_death INTEGER
);

CREATE TABLE poems (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
    author TEXT REFERENCES poet(poet),
    title TEXT NOT NULL, 
    text TEXT NOT NULL
);